dist: xenial
os: linux
#addons:
#  chrome: stable
#before_install:
#  - google-chrome-stable --headless --disable-gpu
git:
  quiet: true
language: java
#services: xvfb
script:
  - mvn exec:java
email:
  recipients:
    zap4ick@gmail